import './globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create-next-app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-navy">{children}</body>
    </html>
  )
}


